# Generated by Django 5.0.6 on 2024-06-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255, null=True)),
                ('content', models.TextField(null=True)),
                ('publication_date', models.DateField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
            ],
            options={
                'db_table': 'News',
            },
        ),
    ]
