# Generated by Django 5.0.6 on 2024-06-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='News',
        ),
    ]
