# Generated by Django 5.0.6 on 2024-06-24 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('additionalMaterialType', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='additional_materials/')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='additionalMaterialType.additionalmaterialtype')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subjects')),
            ],
            options={
                'db_table': 'AdditionalMaterials',
            },
        ),
    ]
