# Generated by Django 5.0.6 on 2024-06-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additionalMaterials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='additionalmaterials',
            table='AdditionalMaterials',
        ),
    ]
