# Generated by Django 5.0.6 on 2024-06-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjectDetails', '0001_initial'),
        ('textbooks', '0001_initial'),
        ('webMaterials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdetails',
            name='textbooks',
            field=models.ManyToManyField(related_name='subject_details_textbooks', to='textbooks.textbooks'),
        ),
        migrations.AddField(
            model_name='subjectdetails',
            name='web_materials',
            field=models.ManyToManyField(related_name='subject_details', to='webMaterials.webmaterials'),
        ),
    ]
