# Generated by Django 5.0.6 on 2024-06-06 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educationForms', '0001_initial'),
        ('studyCycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('number_of_students', models.IntegerField(null=True)),
                ('education_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educationForms.educationforms')),
                ('study_cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studyCycles.studycycles')),
            ],
        ),
    ]
