# Generated by Django 5.0.6 on 2024-06-09 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjectDetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('web_link', models.CharField(max_length=255, null=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjectDetails.subjectdetails')),
            ],
            options={
                'db_table': 'WebMaterials',
            },
        ),
    ]
