# Generated by Django 5.0.6 on 2024-06-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teachers',
            table='Teachers',
        ),
    ]
