# Generated by Django 5.0.6 on 2024-06-19 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='username',
        ),
    ]
